name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - test
    types:
      - closed

jobs:
  publish-charm:
    name: Publish charm to edge
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@1.0.0
        with:
          charmcraft-channel: "latest/stable"
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      #- name: Select charmhub channel
      #  uses: canonical/charming-actions/channel@1.0.0
      #  id: channel
      - name: Upload charm to charmhub
        uses: sanchezfdezjavier/charming-actions/upload-charm@fix-upload-image-false
        with:
          charmcraft-channel: "latest/stable"
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          upload-image: "false"
          channel: "edge"
